### ISSUE TITLE
Pipeline stops after SV calling

### ISSUE THREAD

**Issue by YY-SONG0718** [mskilab-org/nf-jabba#5]
### Description of the bug

Dear maintainer,

Thanks for creating this pipeline! I would like to run it on some BAM files to get JaBbA CNV calls. I managed to run the SV calling by SVABA, but the pipeline said that it was completed after the SV calling when ascat and JaBbA were not run. 

These are the result directories that I currently have:

`Coverages  Hetpileups  msisensorpro  pipeline_info  SV_calling  tabix`

The `Coverages/Dryclean_normal/`  and `Coverages/Dryclean_tumor/` have subdirectories for each sample, but these directories are empty. Could this be the issue?

Meanwhile, may I please confirm that I need to manually add CPLEX to the Docker container, so to create my own container for running the pipeline?

Thank you for your help!

Kind regards,
Yuyao

### Command used and terminal output

```console
nextflow run mskilab-org/nf-jabba -profile singularity -c lsf.config --input samplesheet_jabba_nf.csv --outdir ${out_dir}  --tools svaba,hetpileups,fragcounter,dryclean,cbs,ascat,jabba --genome GATK.GRCh38 --step sv_calling -resume
```

### Relevant files

samplesheet_jabba_nf.csv columns:
`bam,bai,sample,patient,status`

### System information

Nextflow version: 23.10.0
OS: Rocky Linux 8.5
Hardware: HPC
Executor: LSF
Version mskilab-org/nf-jabba: v1.0dev-g90a4c70

**Comment by isidroc** [comment]
Hi team, any news about this bug? Thanks a lot!

**Comment by tanubrata** [comment]
Hi Yuyao,

Glad you are using the pipeline. It seems like an issue with the Dryclean module that you are getting. We recently addressed the issue regarding this package and just pushed a new commit for this pipeline, should fix the issue now. 

Yes, you have to modify the JaBbA docker container since JaBbA depends on CPLEX optimizer, and since its a proprietary software we cannot share it with the container. You can find how to do it in the README.

Tanubrata
